import { mostrarnumeros as ejercicio1 } from "./ejercicio1.js";
import { sumarNumeros as ejercicio2 } from "./ejercicio2.js";
import { mostrarPares as ejercicio3 } from "./ejercicio3.js";
import { tablaMultiplicar as ejercicio4 } from "./ejercicio4.js";
import { calcularFactorial as ejercicio5 } from "./ejercicio5.js";
import { procesarNumero as ejercicio6 } from "./ejercicio6.js";
import { cargarSuma, mostrarSuma as ejercicio7 } from "./ejercicio7.js";
import { procesarLimite as ejercicio8 } from "./ejercicio8.js";
import { mostrarPotencia as ejercicio9 } from "./ejercicio9.js";
import { procesarTerminos as ejercicio10 } from "./ejercicio10.js";
import { procesarVector as ejercicio11 } from "./ejercicio11.js";
import { mostrarMaximo as ejercicio12 } from "./ejercicio12.js";
import { procesarBusqueda as ejercicio13 } from "./ejercicio13.js";
import { reverseArray as ejercicio14 } from "./ejercicio14.js";
import { countEvenNumbers as ejercicio15 } from "./ejercicio15.js";
import { calculateAverage as ejercicio16 } from "./ejercicio16.js";
import { procesarDuplicados as ejercicio17 } from "./ejercicio17.js";
import { procesarOrdenamiento as ejercicio18 } from "./ejercicio18.js";
import { procesarProducto as ejercicio19 } from "./ejercicio19.js";
import { contarVocales as ejercicio20 } from "./ejercicio20.js";
import { procesarMatriz as ejercicio21 } from "./ejercicio21.js";
import { calcularProductoPunto as ejercicio22 } from "./ejercicio22.js";
import { procesarConvolucion as ejercicio23 } from "./ejercicio23.js";
import { ejecutarBusquedaBinaria as ejercicio24 } from "./ejercicio24.js";
import { rotarVector as ejercicio25 } from "./ejercicio25.js";
import { encontrarSubarrayMaximo as ejercicio26 } from "./ejercicio26.js";
import { combinarVectores as ejercicio27 } from "./ejercicio27.js";
import { encontrarPrimos as ejercicio28 } from "./ejercicio28.js";
import { multiplicarMatrices as ejercicio29 } from "./ejercicio29.js";
import { ordenarPorMezcla as ejercicio30 } from "./ejercicio30.js";


export {
    ejercicio1, ejercicio2, ejercicio3, ejercicio4, ejercicio5,
    ejercicio6, ejercicio7, ejercicio8, ejercicio9, ejercicio10,
    ejercicio11, ejercicio12, ejercicio13, ejercicio14, ejercicio15,
    ejercicio16, ejercicio17, ejercicio18, ejercicio19, ejercicio20,
    ejercicio21, ejercicio22, ejercicio23, ejercicio24, ejercicio25,
    ejercicio26, ejercicio27, ejercicio28, ejercicio29, ejercicio30,
    
};
